[package]
name = "pm2rc"
version = "0.1.0"
edition = "2024"

[profile.release]
strip = true
lto=true
opt-level = 'z'
codegen-units = 1
panic = "abort"

[dependencies]
serde="1.0.219"
serde_json="1.0.140"
serde_derive="1.0.219"